config/routes.rb
Rails.application.routes.draw do
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :rooms do
    resources :messages
  end
  resources :users
  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
  before_create :confirm_participant
  has_many_attached :attachments, dependent: :destroy
  # validate :validate_attachment_filetypes

  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end
  
  def chat_attachment(index)
    target = attachments[index]
    return unless attachments.attached?
    # return target if target.content_type.eql?('image/gif')  #if you use this then remove if image/gif condition

    if target.image?
      target.variant(resize_to_limit: [150, 150]).processed
    elsif target.video?
      target.variant(resize_to_limit: [150, 150]).processed
    end
  end
  
  # private
  # def validate_attachment_filetypes
  #   return unless attachments.attached?
    
  #   attachments.each do |attachment|
  #     unless attachment.content_type.in?(%w[image/jpeg image/png image/gif video/mp4 audio/mp3])
  #       errors.add(:attachments, 'must be a JPEG, PNG, GIF, MP3 or MP4')
  #     end
  #   end
  # end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :participants, dependent: :destroy
  after_create_commit { broadcast_if_public }
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  # after_create_commit {broadcast_append_to "rooms"}

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end 

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages
	validates_uniqueness_of :username
	scope :all_except, ->(user) { where.not(id: user) }
	after_create_commit { broadcast_append_to "users" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

	def current_user
		if session[:user_id]
			@current_user  = User.find(session[:user_id])
		end
	end

	def log_in(user)
		session[:user_id] = user.id
		@current_user = user
		redirect_to root_path
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @current_user = current_user
    @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id], attachments: msg_params[:attachments])
  end

  private

  def msg_params
    params.require(:message).permit(:content, attachments: [] )
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @current_user = current_user
    redirect_to '/signin' unless @current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @messages = @single_room.messages
  
    render "index"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:session][:username])
    if user
      log_in(user)
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
      @user = User.find(params[:id])
      @current_user = current_user
      @rooms = Room.public_rooms
      @users = User.all_except(@current_user)
      @room = Room.new
      @message = Message.new
      @room_name = get_name(@user, @current_user)
      @single_room = Room.where(name: @room_name) || Room.create_private_room([@user, current_user], @room_name)
      @messages = @single_room.messages    
      
      render "rooms/index"
   end
   
   private
   def get_name(user1, user2) 
      users = [user1, user2].sort 
      "private_#{users[0].id}_#{users[1].id}"
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      <%= ".msg-#{current_user&.id}" %> {
        background-color: #c63662 !important;
        padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end
      }
    </style>
  </head>

  <body style="background-color: #C5C5C5">
    <div class="container p-4" >
      <%= render "shared/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %>" >
    <% unless message.room.is_private %>
      <h6 class="name"> <%= message.user.username %> </h6>
    <% end %>
    <div>
      <%= message.content %>
    </div>
    <% if message.attachments.attached? %>
      <% message.attachments.each_with_index do |attachment, index| %>
        <% if attachment.content_type.eql?("image/gif") %>
          <div class="gifContainer">
            <%= image_tag(url_for(attachment), style: 'height:auto; width:100%') %>
          </div> 
        <% elsif attachment.image? %>
          <%= image_tag(message.chat_attachment(index)) %>
        <% elsif attachment.video? %>
          <%= video_tag(url_for(attachment), style:'height:auto; width:100%', controls:'') %>
        <% elsif attachment.audio? %>
          <%= audio_tag(url_for(attachment), controls: '') %>
        <% else %>
          <%= link_to attachment.filename, url_for(attachment), style:"text-decoration: none; color: #fff" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/messages/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class: "d-flex", data: { controller: "reset-form emoji-picker", action: "turbo:submit-end->reset-form#reset" }, id: "message-form" ) do |f| %>
  
  <div id="attachment-previews" data-controller="message-preview" data-action="message-preview#preview">
  </div>
  
  <%= content_tag(:i, nil, id: "audio-record-button", class: "fa fa-microphone") %>

  <div class="image-upload">
    <label for="message_attachments" class="plusSize">
    <i class="fa fa-plus-circle"></i>
    </label>
    <%= f.file_field(:attachments, multiple: true, data:{controller: "message-preview", action:"change->message-preview#preview"}, direct_upload: true) %>
  </div>

  <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off', placeholder: "Send a message...", data: {
    emoji_picker_target: "input"} %>
    <%= content_tag(:div, "", class:"pickerContainer", data: {emoji_picker_target: "pickerContainer"})%>
    <span class="emoji-picker-container"></span>
 
    <button type="submit" class="submit_button" data-disable_with= false data-controller="message-preview" data-action="click->message-preview#clearPreviews">
      <span><i class="fa-solid fa-paper-plane"></i></span>
    </button>
    
  <% end %>
</div>

app/views/rooms/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/rooms/_room.html.erb
<li class="list-group-item bgc">
    <%= link_to room.name, room, class: "text-decoration-none text-light" %>
</li>

app/views/rooms/index.html.erb
<div class="row">
    <div class="col-md-3 bgcol">
        <h4 class="text-light">Users </h4>
        <div class="mb-3">
            <%= turbo_stream_from "users" %>
            <div id="users">
                <ul class="list-group list-group-flush">
                <%= render @users %>
                </ul>
            </div>
        </div>
        <div class="user-room" style="width: 16rem;">
            <%= render partial: "rooms/new_room_form" %>
            <h4 class="text-light mt-3">Rooms </h4>
            <div>
               <%= turbo_stream_from "rooms" %>
               <div id="rooms">
                   <ul class="list-group list-group-flush">
                       <%= render @rooms %>
                   </ul>
               </div>
            </div>
        </div>
    </div>
    <div class="col-md-9 bg-color text-light">
        <% if @single_room %>
        <h4 class="text-center text-light"> <%= @user&.username || @single_room.name %> </h4>
        <hr/>
            <%= turbo_stream_from @single_room %>
            <div id="messages">
                <%= render @messages %>
            </div>
            <%= render partial: "messages/new_message_form" %>
        <% end %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" style="width: 1116px; margin-left: -12px;">
	<% if @current_user.present? %>
		<div class="container-fluid">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link text-light" aria-current="page" href="#">Rails chat app</a>
				</li>

				<li class="nav-item">
					<a class="nav-link text-light" aria-current="page" href="#">
					   <%= @current_user.username %>
					</a>
				</li>
			</ul>
			<ul class="navbar-nav mb-2 mb-lg-0">
				<li class="nav-item">
					<div class="bglogout">
						<%= link_to signout_path,  :method => :delete, data: {confirm: "Are you sure"}, class: "signout nav-link text-dark" do %>
							<i class="fa-solid fa-right-from-bracket"></i>
						<% end %>
					</div>
				</li>
			</ul>
		</div>
	<% end %> 
</nav>

app/views/users/_user.html.erb
<li class="list-group-item bgc"> <%= link_to user.username, user,  class: "text-decoration-none text-light" %> </li>